## Init & Data Preprocessing

In [30]:
#when you extract dataSet, plz make cycle one by one, assuring validation set has all 3 labels

import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import tensorflow as tf
import pandas as pd
import  numpy as np
gpu_options = tf.GPUOptions(allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))

train=pd.read_csv('dataSet_h2_methAceEth.csv', header=None) #pandas is easy to watch variables
X_pd=train.loc[:, 0:15]
y_pd=train.loc[:, 16]
X=X_pd.values
y=y_pd.values

# print X_pd.describe()
# print y_pd.describe()



np.set_printoptions(threshold=5)
label=y
X_train=np.zeros((1110,4,4)) #3d


for i in range(1110):
    X_train[i]=np.reshape(X[i],(4,4))
# for i in range(1110): # reset the label y
#     if y[i]<=6 or y[i]==13:
#         label[i]=0
#     elif y[i]>=7 and y[i]<=12:
#         label[i]=1
#     else:
#         label[i]=2

X1=X_train
label1=label
X_pd
# X1=np.tile(X_train,(100,1,1))
# label1=np.tile(label,(100,1))




0        1        2        3        4        5        6        7   \
0     0.79960  0.84421  0.50632  0.49032  1.02630  0.92324  0.88953  0.88840   
1     0.86546  0.80380  0.54682  0.46249  0.97944  0.90404  0.79605  0.73519   
2     0.88944  0.80383  0.52970  0.47202  1.00970  0.85580  0.80735  0.78196   
3     0.92319  0.78592  0.51414  0.45812  0.99082  0.81746  0.83252  0.69711   
4     0.90073  0.80946  0.53863  0.47979  0.92878  0.81343  0.80389  0.70091   
5     0.90831  0.81241  0.55323  0.49323  0.98676  0.80569  0.80323  0.70080   
6     0.91158  0.80667  0.54148  0.46308  1.00530  0.79818  0.81337  0.62828   
7     0.91830  0.82503  0.57048  0.49327  1.08940  0.80564  0.81197  0.66943   
8     0.91126  0.82238  0.56517  0.48548  0.97158  0.79104  0.86243  0.63276   
9     0.92140  0.86718  0.59967  0.57203  0.97475  0.80723  0.83747  0.65968   
10    0.75548  0.83171  0.45458  0.38426  1.00000  0.93076  0.84928  0.85523   
11    0.85232  0.77809  0.48025  0.40039  1.00430  0.89026  0.77296  0.69078   
12    0.88136  0.78217  0.46320  0.42377  0.98684  0.84407  0.78216  0.69976   
13    0.88748  0.77598  0.45614  0.40024  1.00460  0.80558  0.80639  0.65812   
14    0.89894  0.79145  0.49250  0.43966  0.98138  0.79789  0.78167  0.65849   
15    0.90440  0.79566  0.50643  0.44682  1.00900  0.78947  0.78516  0.65064   
16    0.90880  0.79202  0.50955  0.43679  0.99467  0.78506  0.77585  0.62274   
17    0.91403  0.81074  0.53365  0.45536  0.95064  0.79409  0.79571  0.63110   
18    0.90736  0.78919  0.53084  0.45321  0.96942  0.78332  0.78075  0.59569   
19    0.91763  0.83973  0.55915  0.55401  0.97367  0.79513  0.80390  0.62680   
20    0.72421  0.77852  0.40764  0.33640  0.97551  0.93198  0.80561  0.77644   
21    0.83964  0.74686  0.44177  0.35707  1.00000  0.87641  0.74718  0.64006   
22    0.87147  0.75562  0.42367  0.38683  0.99528  0.83061  0.75103  0.65258   
23    0.88597  0.75175  0.42435  0.37748  0.98629  0.79363  0.74483  0.61777   
24    0.89096  0.76806  0.45337  0.45421  1.00690  0.78906  0.75436  0.61511   
25    0.89869  0.77579  0.46231  0.40864  1.04350  0.77981  0.75867  0.59920   
26    0.90296  0.76667  0.47702  0.40451  0.98955  0.76970  0.76241  0.55683   
27    0.90842  0.78959  0.50380  0.43271  0.96986  0.78056  0.77090  0.59593   
28    0.90110  0.78427  0.49623  0.42686  0.96644  0.76706  0.74829  0.55621   
29    0.91424  0.83002  0.52797  0.51748  0.97047  0.78285  0.72249  0.58873   
...       ...      ...      ...      ...      ...      ...      ...      ...   
1080  0.93645  0.88817  0.76180  0.73626  0.94576  0.79078  0.87671  0.86546   
1081  0.92979  0.87160  0.56899  0.55259  0.94150  0.82208  0.84780  0.83032   
1082  0.92708  0.86379  0.58976  0.55604  0.94679  0.81373  0.85709  0.80383   
1083  0.92399  0.84654  0.56186  0.54729  0.94133  0.80723  0.77799  0.77594   
1084  0.91860  0.83047  0.55641  0.53330  0.93950  0.79626  0.85917  0.74636   
1085  0.91321  0.82238  0.54570  0.52327  0.93757  0.78959  0.76656  0.72460   
1086  0.91032  0.80928  0.53366  0.50660  0.93428  0.78285  0.73452  0.69860   
1087  1.02590  1.06170  1.16410  1.15810  1.02150  1.03240  1.07200  1.08810   
1088  1.05790  1.10690  1.22350  1.20480  1.04470  1.05090  1.10880  1.10750   
1089  1.09650  1.15000  1.24720  1.22260  1.06480  1.08210  1.12310  1.12730   
1090  1.10630  1.16320  1.25290  1.21570  1.07330  1.11560  1.08300  1.14040   
1091  1.10850  1.17300  1.25760  1.20710  1.08110  1.12940  1.15310  1.14940   
1092  1.10950  1.19720  1.25600  1.19610  1.08350  1.12710  1.16000  1.14330   
1093  0.88730  0.85858  0.51609  0.50437  0.91537  0.78566  0.88120  0.88869   
1094  0.93019  0.88121  0.80120  0.78725  0.93266  0.85018  0.88001  0.90878   
1095  0.89716  0.92748  0.90945  0.89586  0.94545  0.85660  0.95819  0.93765   
1096  0.92455  0.87243  0.75050  0.72740  0.93272  0.82272  0.87706  0.87497   
1097  0.95730  0.93265  0.87316  0.85889  0.95715  0.85193  0.93429  0.93385   
1098  0.908

## Model Part, haven't shuffled yet

In [49]:
print(X1.shape)

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(1024,
                        #input_shape=(41000,),
                        activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(1024, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(7, activation=tf.nn.softmax)
])

#todo test all optimizer

# model.compile(
#     optimizer='adam',
#     #optimizer=tf.keras.optimizers.SGD(lr=0.001, momentum=0.9, nesterov=True),
#                 #loss=tf.keras.losses.categorical_crossentropy,
#                 loss='sparse_categorical_crossentropy',
#                 #loss=tf.losses.softmax_cross_entropy,
#                 # pred=tf.nn.softmax(tf.add(tf.matmul(X1,W),b)) ,
#                 # cost =tf.reduce_mean(-tf.reduce_sum(label1*tf.log(pred),reduction_indices=1)),
#                 #loss='categorical_crossentropy',
#               metrics=['accuracy'])

# np.set_printoptions(threshold='none')
# print(X1.shape)
# #print(label1)

# model.fit(X1, label1, epochs=5)
# print(model.evaluate(X1, label1))

# print(label1[294])
# #print(model.predict_classes(X1[294],batch_size=10,verbose=0))


(1110, 4, 4)


## Creating 100 times dataSet, using randint
## Shuffling the dataSet

In [57]:
tess=[]
for i in range(4):
    #tess[i]=9
    tess.append(i)

tess=np.array(tess)
tess.shape

(4,)

In [21]:
#test
import random
#tess=[]
# for i in range(10):
#     tess.append(shuffle(range(10)))  
li=range(10)    
print li
tess=random.shuffle(li)
print tess
print li
    

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
None
[2, 5, 4, 9, 1, 7, 3, 6, 8, 0]


In [50]:
model.compile(
    optimizer='adam',
    #optimizer=tf.keras.optimizers.SGD(lr=0.001, momentum=0.9, nesterov=True),
                #loss=tf.keras.losses.categorical_crossentropy,
                loss='sparse_categorical_crossentropy',
                #loss=tf.losses.softmax_cross_entropy,
                # pred=tf.nn.softmax(tf.add(tf.matmul(X1,W),b)) ,
                # cost =tf.reduce_mean(-tf.reduce_sum(label1*tf.log(pred),reduction_indices=1)),
                #loss='categorical_crossentropy',
              metrics=['accuracy'])

In [37]:
x2=np.array(x2)

In [51]:
#X1=np.tile(X_train,(100,1,1))
#label1=np.tile(label,(100,1))
gpu_options = tf.GPUOptions(allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
from random import randint,shuffle
X2= []
label2= []
random_fetch=range(1110)
shuffle(random_fetch)

for i in range(1110):
    X2.append(np.reshape(X[random_fetch[i]],(4,4)))
    label2.append(label[random_fetch[i]])
        
X2=np.array(X2)
label2=np.array(label2)

np.set_printoptions(threshold='none')

model.fit(X2, label2, validation_split=0.1, epochs=5)
model.evaluate(X2,label2)

# print label1[368:409]

Train on 999 samples, validate on 111 samples
Epoch 1/5
999/999 [==============================] - 1s 681us/step - loss: 1.6371 - acc: 0.3353 - val_loss: 1.2643 - val_acc: 0.4234
Epoch 2/5
999/999 [==============================] - 0s 236us/step - loss: 1.2035 - acc: 0.5235 - val_loss: 1.0772 - val_acc: 0.6306
Epoch 3/5
999/999 [==============================] - 0s 208us/step - loss: 1.0530 - acc: 0.5616 - val_loss: 0.9475 - val_acc: 0.6396
Epoch 4/5
999/999 [==============================] - 0s 245us/step - loss: 0.9717 - acc: 0.5816 - val_loss: 0.8387 - val_acc: 0.6306
Epoch 5/5
1110/1110 [==============================] - 0s 75us/step


[0.7745364340575965, 0.6990990985621203]

 ### Appently, the data performance between meth part, ace part and eth part are not that good, i.e. if we use single raw data set extracting from a single experience. The performance would be great (shown as below) because of the data correlation and sigularity. 

### In a word, we can not determine if the data presented from our experiments can differ from each other that well. That is a very significant prerequsite. Assuming there are better network structure to explore, I think we can enhance this MLP with the following aspects.

## 1. More reasonable normalization method. Maybe instead of using the last time point, there are better solution.
## 2. Adding more layers as well as tuning parameters for better performance. 
## 3. When we do shuffling, try to use random instead of grid seach.
## 4. Increasing the number of samples in trainingSet, but it has been experienced before and it was not that effective.

In [124]:
train_a=X1[410:820,:,:] # acetone
label_a=label1[410:820]
# print train_a
# print label_a

[[[0.94441 0.90067 0.64936 0.6239 ]
  [0.95603 0.84325 0.78641 0.85984]
  [0.90358 0.63733 0.80444 0.57256]
  [0.73942 0.79203 0.8778  0.87557]]

 [[0.94158 0.88355 0.6505  0.62551]
  [0.95389 0.83295 0.81981 0.83377]
  [0.99001 0.63492 0.79048 0.57207]
  [0.71759 0.76916 0.85577 0.85619]]

 [[0.95342 0.87063 0.64334 0.60269]
  [0.94493 0.82048 0.83094 0.80333]
  [0.86861 0.60787 0.8     0.55181]
  [0.69713 0.7462  0.83458 0.83373]]

 [[0.91882 0.86171 0.652   0.61634]
  [0.94785 0.80787 0.80545 0.78076]
  [0.91356 0.61083 0.78495 0.5303 ]
  [0.6811  0.72801 0.81789 0.81712]]

 [[0.92857 0.85238 0.6066  0.58328]
  [0.94584 0.80562 0.74777 0.76278]
  [0.88403 0.57969 0.78453 0.52493]
  [0.66525 0.71235 0.79975 0.80029]]

 [[0.92352 0.83989 0.59101 0.56494]
  [0.9423  0.79294 0.80654 0.73763]
  [0.85761 0.52471 0.77193 0.50135]
  [0.65214 0.69651 0.78499 0.78481]]

 [[1.0363  1.0782  1.2364  1.2231 ]
  [1.0317  1.0462  1.1721  1.1204 ]
  [1.0448  1.2712  1.2651  1.4809 ]
  [1.1929  1.164

In [109]:
tess=label1[0:2]
print tess

[0 0]


In [125]:
label_a.shape

(410,)

In [ ]:
gpu_options = tf.GPUOptions(allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
from random import randint,shuffle
# X2= []
# label2= []
# random_fetch=range(410)
# shuffle(random_fetch)
# train_ace=X1
# for i in range(410):
#     X2.append(np.reshape(X[random_fetch[i]],(4,4)))
#     label2.append(label[random_fetch[i]])        
# X2=np.array(X2)
# label2=np.array(label2)

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(1024,
                        #input_shape=(41000,),
                        activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(1024, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(3, activation=tf.nn.softmax)
])

for i in range(410):
    if label_a[i]==3:
        label_a[i]=1
    elif label_a[i]==4:
        label_a[i]=2

train_a=np.tile(train_a,(100,1,1))
label_a=np.tile(label_a,(100,))

np.set_printoptions(threshold='none')

model.compile(
    optimizer='adam',
    #optimizer=tf.keras.optimizers.SGD(lr=0.001, momentum=0.9, nesterov=True),
                #loss=tf.keras.losses.categorical_crossentropy,
                loss='sparse_categorical_crossentropy',
                #loss=tf.losses.softmax_cross_entropy,
                # pred=tf.nn.softmax(tf.add(tf.matmul(X1,W),b)) ,
                # cost =tf.reduce_mean(-tf.reduce_sum(label1*tf.log(pred),reduction_indices=1)),
                #loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_a, label_a, validation_split=0.1, epochs=5)
model.evaluate(train_a,label_a)

# print label1[368:409]

Train on 36900 samples, validate on 4100 samples
Epoch 1/5
36900/36900 [==============================] - 10s 262us/step - loss: 0.2234 - acc: 0.8937 - val_loss: 0.1429 - val_acc: 0.9268
Epoch 2/5
36900/36900 [==============================] - 7s 198us/step - loss: 0.1693 - acc: 0.9180 - val_loss: 0.1838 - val_acc: 0.9073
Epoch 3/5
36900/36900 [==============================] - 8s 225us/step - loss: 0.1495 - acc: 0.9306 - val_loss: 0.1109 - val_acc: 0.9512
Epoch 4/5
36900/36900 [==============================] - 8s 211us/step - loss: 0.1324 - acc: 0.9404 - val_loss: 0.1613 - val_acc: 0.9146
Epoch 5/5
12000/41000 [=======>......................] - ETA: 2s

In [102]:
label_a.s

(409,)

In [68]:
tess=[]
tess=np.array(tess)

In [77]:
tess

array([], dtype=int64)

In [4]:
sess.close()

In [51]:
label1

array([[0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [1.],

In [70]:
sess = tf.Session()
#print sess.run(model.fit)
sess.close()

In [26]:
test=np.reshape(X1[399],(1,4,4))

In [6]:
test.shape

(1, 4, 4)

In [25]:
np.set_printoptions(threshold='none')
#label1
y

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14,
       14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19,
       19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23,
       23, 23, 23, 23, 23

In [27]:
label1[399]

array([2.])

In [9]:
print(model.predict(test,batch_size=10,verbose=0))

[[5.5517238e-03 7.3542947e-06 9.9444085e-01]]


In [28]:
print(model.predict_classes(test,batch_size=10,verbose=0))

[2]
