## Init & Data Preprocessing

In [1]:
#when you extract dataSet, plz make cycle one by one, assuring validation set has all 3 labels

import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import tensorflow as tf
import pandas as pd
import  numpy as np
gpu_options = tf.GPUOptions(allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))

train=pd.read_csv('dataSet_h2_methAceEth.csv', header=None) #pandas is easy to watch variables
X_pd=train.loc[:, 0:15]
y_pd=train.loc[:, 16]
X=X_pd.values
y=y_pd.values

# print X_pd.describe()
# print y_pd.describe()



np.set_printoptions(threshold=5)
label=y
X_train=np.zeros((1110,4,4)) #3d


for i in range(1110):
    X_train[i]=np.reshape(X[i],(4,4))
# for i in range(1110): # reset the label y
#     if y[i]<=6 or y[i]==13:
#         label[i]=0
#     elif y[i]>=7 and y[i]<=12:
#         label[i]=1
#     else:
#         label[i]=2

X1=X_train
label1=label
#X_pd
# X1=np.tile(X_train,(100,1,1))
# label1=np.tile(label,(100,1))




## Model Part, haven't shuffled yet

In [2]:
print(X1.shape)

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(1024,
                        #input_shape=(41000,),
                        activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(1024, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(7, activation=tf.nn.softmax)
])

#todo test all optimizer

# model.compile(
#     optimizer='adam',
#     #optimizer=tf.keras.optimizers.SGD(lr=0.001, momentum=0.9, nesterov=True),
#                 #loss=tf.keras.losses.categorical_crossentropy,
#                 loss='sparse_categorical_crossentropy',
#                 #loss=tf.losses.softmax_cross_entropy,
#                 # pred=tf.nn.softmax(tf.add(tf.matmul(X1,W),b)) ,
#                 # cost =tf.reduce_mean(-tf.reduce_sum(label1*tf.log(pred),reduction_indices=1)),
#                 #loss='categorical_crossentropy',
#               metrics=['accuracy'])

# np.set_printoptions(threshold='none')
# print(X1.shape)
# #print(label1)

# model.fit(X1, label1, epochs=5)
# print(model.evaluate(X1, label1))

# print(label1[294])
# #print(model.predict_classes(X1[294],batch_size=10,verbose=0))


(1110, 4, 4)


## Creating 100 times dataSet, using randint
## Shuffling the dataSet

In [57]:
tess=[]
for i in range(4):
    #tess[i]=9
    tess.append(i)

tess=np.array(tess)
tess.shape

(4,)

In [21]:
#test
import random
#tess=[]
# for i in range(10):
#     tess.append(shuffle(range(10)))  
li=range(10)    
print li
tess=random.shuffle(li)
print tess
print li
    

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
None
[2, 5, 4, 9, 1, 7, 3, 6, 8, 0]


In [3]:
model.compile(
    optimizer='adam',
    #optimizer=tf.keras.optimizers.SGD(lr=0.001, momentum=0.9, nesterov=True),
                #loss=tf.keras.losses.categorical_crossentropy,
                loss='sparse_categorical_crossentropy',
                #loss=tf.losses.softmax_cross_entropy,
                # pred=tf.nn.softmax(tf.add(tf.matmul(X1,W),b)) ,
                # cost =tf.reduce_mean(-tf.reduce_sum(label1*tf.log(pred),reduction_indices=1)),
                #loss='categorical_crossentropy',
              metrics=['accuracy'])

In [37]:
x2=np.array(x2)

In [51]:
#X1=np.tile(X_train,(100,1,1))
#label1=np.tile(label,(100,1))

# if run 1110 samples, make sure the input labels are correct and not modified

gpu_options = tf.GPUOptions(allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
from random import randint,shuffle
X2= []
label2= []
random_fetch=range(1110)
shuffle(random_fetch)

for i in range(1110):
    X2.append(np.reshape(X[random_fetch[i]],(4,4)))
    label2.append(label[random_fetch[i]])
        
X2=np.array(X2)
label2=np.array(label2)

np.set_printoptions(threshold='none')

model.fit(X2, label2, validation_split=0.1, epochs=5)
model.evaluate(X2,label2)

# print label1[368:409]

Train on 999 samples, validate on 111 samples
Epoch 1/5
999/999 [==============================] - 1s 681us/step - loss: 1.6371 - acc: 0.3353 - val_loss: 1.2643 - val_acc: 0.4234
Epoch 2/5
999/999 [==============================] - 0s 236us/step - loss: 1.2035 - acc: 0.5235 - val_loss: 1.0772 - val_acc: 0.6306
Epoch 3/5
999/999 [==============================] - 0s 208us/step - loss: 1.0530 - acc: 0.5616 - val_loss: 0.9475 - val_acc: 0.6396
Epoch 4/5
999/999 [==============================] - 0s 245us/step - loss: 0.9717 - acc: 0.5816 - val_loss: 0.8387 - val_acc: 0.6306
Epoch 5/5
1110/1110 [==============================] - 0s 75us/step


[0.7745364340575965, 0.6990990985621203]

 ### Appently, the data performance between meth part, ace part and eth part are not that good, i.e. if we use single raw data set extracting from a single experience. The performance would be great (shown as below) because of the data correlation and sigularity. 

### In a word, we can not determine if the data presented from our experiments can differ from each other that well. That is a very significant prerequsite. Assuming there are better network structure to explore, I think we can enhance this MLP with the following aspects.

## 1. More reasonable normalization method. Maybe instead of using the last time point, there are better solution.
## 2. Adding more layers as well as tuning parameters for better performance. 
## 3. When we do shuffling, try to use random search instead of grid seach.
## 4. Increasing the number of samples in trainingSet, however it has been experienced before and it was not that effective.

In [77]:
train_a=X1[410:820,:,:] # acetone
label_a=label1[410:820]
# print train_a
# print label_a

In [78]:
np.set_printoptions(threshold='none')
print train_a.shape
print label_a.shape
print label_a #acetone
print X.shape

(410, 4, 4)
(410,)
[0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1
 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0
 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0
 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2]
(1110, 16)


In [117]:
a=range(10)
shuffle(a)
print a
np.set_printoptions(threshold='none')
label1

[5, 6, 3, 4, 0, 1, 7, 8, 9, 2]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [153]:
#shuffling the cycles for 410,acetone

from random import randint,shuffle
train_a=X1[410:820,:,:] # acetone
label_a=label1[410:820]

X2= []
label2= []
random_fetch=range(10)
shuffle(random_fetch)
train_ace=X1

for i in range(10):
    for k in range(41):
        X2.append(np.reshape(train_a[random_fetch[i]*41+k],(4,4)))
        label2.append(label_a[random_fetch[i]*41+k])   
    
X2=np.array(X2)
label2=np.array(label2)


print random_fetch
np.set_printoptions(threshold=3)
print X2
print label2

[6, 8, 4, 0, 3, 5, 9, 7, 1, 2]
[[[0.94481 0.88999 0.62845 0.61851]
  [0.94975 0.85031 0.86638 0.84484]
  [0.88212 0.59566 0.83041 0.56818]
  [0.74247 0.79077 0.87404 0.86151]]

 [[0.94414 0.87925 0.6363  0.62575]
  [0.94929 0.84145 0.84833 0.82177]
  [0.88774 0.59033 0.84615 0.5848 ]
  [0.73147 0.7761  0.85601 0.84524]]

 [[0.93855 0.86564 0.63682 0.62302]
  [0.94706 0.82789 0.82617 0.79261]
  [0.87177 0.61166 0.84106 0.55352]
  [0.70881 0.75298 0.83238 0.82224]]

 ...

 [[0.97181 0.9269  0.87238 0.84911]
  [0.95846 0.8369  0.92743 0.92821]
  [0.93366 0.87726 0.97436 0.90618]
  [0.89693 0.93203 0.94225 0.93108]]

 [[0.9296  0.83876 0.72961 0.71035]
  [0.92791 0.81205 0.81967 0.8047 ]
  [0.88813 0.72695 0.78    0.67223]
  [0.74821 0.79422 0.83133 0.82647]]

 [[1.0669  0.93721 0.86247 0.8325 ]
  [0.95956 0.83415 0.91571 0.94534]
  [0.97249 0.85955 1.      0.89398]
  [0.90379 0.94365 0.95392 0.94399]]]
[0 0 0 ... 2 2 2]


In [76]:
tess=np.array([[1,2,3],[4,5,6]])
t=np.tile(tess,(2,1))
t

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [166]:
np.set_printoptions(threshold='none')
print label_a
train_sub=train_a[0:369,:,:]
label_sub=label_a[0:369]  
print label_a[409]

[0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1
 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0
 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0
 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2]
2


In [195]:
train_sub=train_a[0:369,:,:]
train_lab=label_a[0:369]
valid_sub=train_a[369:410,:,:]
valid_lab=label_a[369:410]
m1=np.tile(train_sub,(100,1,1))
m2=np.tile(valid_sub,(100,1,1))
m3=np.tile(train_lab,(100,))
m4=np.tile(valid_lab,(100,))
tt=np.concatenate([m3,m4])
t2=np.concatenate([m1,m2])
#tt.shapetrain_sub=train_a[0:369,:,:]
train_lab=label_a[0:369]
valid_sub=train_a[369:410,:,:]
valid_lab=label_a[369:410]
m1=np.tile(train_sub,(100,1,1))
m2=np.tile(valid_sub,(100,1,1))
m3=np.tile(train_lab,(100,))
m4=np.tile(valid_lab,(100,))
tt=np.concatenate([m3,m4])
t2=np.concatenate([m1,m2])
#label_a=np.concatenate([m3,m4], axis=1)

In [199]:
gpu_options = tf.GPUOptions(allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
from random import randint,shuffle

train_a=X2
label_a=label2

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(1024,
                        #input_shape=(41000,),
                        activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(1024, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(3, activation=tf.nn.softmax)
])

for i in range(410):
    if label_a[i]==3:
        label_a[i]=1
    elif label_a[i]==4:
        label_a[i]=2

# tiling the data
train_sub=train_a[0:369,:,:]
train_lab=label_a[0:369]
valid_sub=train_a[369:410,:,:]
valid_lab=label_a[369:410]
m1=np.tile(train_sub,(100,1,1))
m2=np.tile(valid_sub,(100,1,1))
m3=np.tile(train_lab,(100,))
m4=np.tile(valid_lab,(100,))
label_input=np.concatenate([m3,m4])
train_input=np.concatenate([m1,m2])

train_input1=np.tile(train_a,(100,1,1))
label_input1=np.tile(label_a,(100,))


np.set_printoptions(threshold='none')

model.compile(
    optimizer='adam',
    #optimizer=tf.keras.optimizers.SGD(lr=0.001, momentum=0.9, nesterov=True),
                #loss=tf.keras.losses.categorical_crossentropy,
                loss='sparse_categorical_crossentropy',
                #loss=tf.losses.softmax_cross_entropy,
                # pred=tf.nn.softmax(tf.add(tf.matmul(X1,W),b)) ,
                # cost =tf.reduce_mean(-tf.reduce_sum(label1*tf.log(pred),reduction_indices=1)),
                #loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_input, label_input, validation_split=0.1, epochs=5)
model.evaluate(train_input,label_input)

# print label1[368:409]

Train on 36900 samples, validate on 4100 samples
Epoch 1/5


InvalidArgumentError: Incompatible shapes: [32,4] vs. [32]
	 [[{{node metrics_19/acc/Equal}} = Equal[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](metrics_19/acc/Max, metrics_19/acc/Cast)]]
	 [[{{node loss_19/output_1_loss/broadcast_weights/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/concat/_2343}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_253_l...ims/concat", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

In [201]:
label_input.shape

(41000, 4, 4)

In [102]:
label_a.s

(409,)

In [69]:
print label_a[394]
model.predict_classes(x=np.reshape(train_a[394],(4,4)))

2


InvalidArgumentError: Matrix size-incompatible: In[0]: [4,4], In[1]: [16,1024]
	 [[{{node MatMul_36}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Reshape_12, MatMul_36/ReadVariableOp)]]
	 [[{{node Softmax_12/_1653}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_77_Softmax_12", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

In [68]:
tess=[]
tess=np.array(tess)

In [77]:
tess

array([], dtype=int64)

In [4]:
sess.close()

In [51]:
label1

array([[0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [1.],

In [70]:
sess = tf.Session()
#print sess.run(model.fit)
sess.close()

In [26]:
test=np.reshape(X1[399],(1,4,4))

In [6]:
test.shape

(1, 4, 4)

In [25]:
np.set_printoptions(threshold='none')
#label1
y

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14,
       14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19,
       19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23,
       23, 23, 23, 23, 23

In [27]:
label1[399]

array([2.])

In [9]:
print(model.predict(test,batch_size=10,verbose=0))

[[5.5517238e-03 7.3542947e-06 9.9444085e-01]]


In [28]:
print(model.predict_classes(test,batch_size=10,verbose=0))

[2]
