## Init & Data Preprocessing

In [2]:
#when you extract dataSet, plz make cycle one by one, assuring validation set has all 3 labels

import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import tensorflow as tf
import pandas as pd
import  numpy as np
gpu_options = tf.GPUOptions(allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))

train=pd.read_csv('dataSet_h2_methAceEth.csv', header=None) #pandas is easy to watch variables
X_pd=train.loc[:, 0:15]
y_pd=train.loc[:, 16]
X=X_pd.values
y=y_pd.values

# print X_pd.describe()
# print y_pd.describe()



np.set_printoptions(threshold=5)
label=y
X_train=np.zeros((1110,4,4)) #3d


for i in range(1110):
    X_train[i]=np.reshape(X[i],(4,4))
# for i in range(1110): # reset the label y
#     if y[i]<=6 or y[i]==13:
#         label[i]=0
#     elif y[i]>=7 and y[i]<=12:
#         label[i]=1
#     else:
#         label[i]=2

X1=X_train
label1=label
#X_pd
# X1=np.tile(X_train,(100,1,1))
# label1=np.tile(label,(100,1))




## Model Part, haven't shuffled yet

In [2]:
print(X1.shape)

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(1024,
                        #input_shape=(41000,),
                        activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(1024, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(7, activation=tf.nn.softmax)
])

#todo test all optimizer

# model.compile(
#     optimizer='adam',
#     #optimizer=tf.keras.optimizers.SGD(lr=0.001, momentum=0.9, nesterov=True),
#                 #loss=tf.keras.losses.categorical_crossentropy,
#                 loss='sparse_categorical_crossentropy',
#                 #loss=tf.losses.softmax_cross_entropy,
#                 # pred=tf.nn.softmax(tf.add(tf.matmul(X1,W),b)) ,
#                 # cost =tf.reduce_mean(-tf.reduce_sum(label1*tf.log(pred),reduction_indices=1)),
#                 #loss='categorical_crossentropy',
#               metrics=['accuracy'])

# np.set_printoptions(threshold='none')
# print(X1.shape)
# #print(label1)

# model.fit(X1, label1, epochs=5)
# print(model.evaluate(X1, label1))

# print(label1[294])
# #print(model.predict_classes(X1[294],batch_size=10,verbose=0))


(1110, 4, 4)


## Creating 100 times dataSet, using randint
## Shuffling the dataSet

In [57]:
tess=[]
for i in range(4):
    #tess[i]=9
    tess.append(i)

tess=np.array(tess)
tess.shape

(4,)

In [21]:
#test
import random
#tess=[]
# for i in range(10):
#     tess.append(shuffle(range(10)))  
li=range(10)    
print li
tess=random.shuffle(li)
print tess
print li
    

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
None
[2, 5, 4, 9, 1, 7, 3, 6, 8, 0]


In [3]:
model.compile(
    optimizer='adam',
    #optimizer=tf.keras.optimizers.SGD(lr=0.001, momentum=0.9, nesterov=True),
                #loss=tf.keras.losses.categorical_crossentropy,
                loss='sparse_categorical_crossentropy',
                #loss=tf.losses.softmax_cross_entropy,
                # pred=tf.nn.softmax(tf.add(tf.matmul(X1,W),b)) ,
                # cost =tf.reduce_mean(-tf.reduce_sum(label1*tf.log(pred),reduction_indices=1)),
                #loss='categorical_crossentropy',
              metrics=['accuracy'])

In [37]:
x2=np.array(x2)

In [51]:
#X1=np.tile(X_train,(100,1,1))
#label1=np.tile(label,(100,1))

# if run 1110 samples, make sure the input labels are correct and not modified

gpu_options = tf.GPUOptions(allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
from random import randint,shuffle
X2= []
label2= []
random_fetch=range(1110)
shuffle(random_fetch)

for i in range(1110):
    X2.append(np.reshape(X[random_fetch[i]],(4,4)))
    label2.append(label[random_fetch[i]])
        
X2=np.array(X2)
label2=np.array(label2)

np.set_printoptions(threshold='none')

model.fit(X2, label2, validation_split=0.1, epochs=5)
model.evaluate(X2,label2)

# print label1[368:409]

Train on 999 samples, validate on 111 samples
Epoch 1/5
999/999 [==============================] - 1s 681us/step - loss: 1.6371 - acc: 0.3353 - val_loss: 1.2643 - val_acc: 0.4234
Epoch 2/5
999/999 [==============================] - 0s 236us/step - loss: 1.2035 - acc: 0.5235 - val_loss: 1.0772 - val_acc: 0.6306
Epoch 3/5
999/999 [==============================] - 0s 208us/step - loss: 1.0530 - acc: 0.5616 - val_loss: 0.9475 - val_acc: 0.6396
Epoch 4/5
999/999 [==============================] - 0s 245us/step - loss: 0.9717 - acc: 0.5816 - val_loss: 0.8387 - val_acc: 0.6306
Epoch 5/5
1110/1110 [==============================] - 0s 75us/step


[0.7745364340575965, 0.6990990985621203]

 ### Appently, the data performance between meth part, ace part and eth part are not that good, i.e. if we use single raw data set extracting from a single experience. The performance would be great (shown as below) because of the data correlation and sigularity. 

### In a word, we can not determine if the data presented from our experiments can differ from each other that well. That is a very significant prerequsite. Assuming there are better network structure to explore, I think we can enhance this MLP with the following aspects.

## 1. More reasonable normalization method. Maybe instead of using the last time point, there are better solution.
## 2. Adding more layers as well as tuning parameters for better performance. 
## 3. When we do shuffling, try to use random search instead of grid seach.
## 4. Increasing the number of samples in trainingSet, however it has been experienced before and it was not that effective.

In [3]:
train_a=X1[410:820,:,:] # acetone
label_a=label1[410:820]
# print train_a
# print label_a

In [78]:
np.set_printoptions(threshold='none')
print train_a.shape
print label_a.shape
print label_a #acetone
print X.shape

(410, 4, 4)
(410,)
[0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1
 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0
 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0
 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2]
(1110, 16)


In [117]:
a=range(10)
shuffle(a)
print a
np.set_printoptions(threshold='none')
label1

[5, 6, 3, 4, 0, 1, 7, 8, 9, 2]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [4]:
#shuffling the cycles for 410,acetone

from random import randint,shuffle
train_a=X1[410:820,:,:] # acetone
label_a=label1[410:820]

X2= []
label2= []
random_fetch=range(10)
shuffle(random_fetch)
train_ace=X1

for i in range(10):
    for k in range(41):
        X2.append(np.reshape(train_a[random_fetch[i]*41+k],(4,4)))
        label2.append(label_a[random_fetch[i]*41+k])   
    
X2=np.array(X2)
label2=np.array(label2)


print random_fetch
np.set_printoptions(threshold=3)
print X2
print label2

[8, 4, 2, 3, 1, 9, 5, 0, 6, 7]
[[[0.94114 0.88226 0.65    0.62072]
  [0.94686 0.83944 0.85399 0.82897]
  [0.83181 0.60446 0.80795 0.56787]
  [0.73546 0.77917 0.86772 0.84979]]

 [[0.9435  0.87359 0.65156 0.62804]
  [0.94646 0.83634 0.83714 0.80318]
  [0.84025 0.60131 0.82394 0.57098]
  [0.72719 0.77019 0.84643 0.83205]]

 [[0.93723 0.86001 0.63165 0.6148 ]
  [0.94244 0.82361 0.81623 0.77879]
  [0.87453 0.58389 0.85401 0.56436]
  [0.70387 0.74904 0.82663 0.81177]]

 ...

 [[0.95158 0.9185  0.85387 0.83694]
  [0.95467 0.83009 0.91948 0.90981]
  [0.9375  0.8767  0.96894 0.88601]
  [0.88119 0.91685 0.92529 0.91609]]

 [[0.92299 0.83093 0.71153 0.69601]
  [0.92287 0.79531 0.79699 0.76976]
  [0.83956 0.7068  0.81988 0.67098]
  [0.7277  0.77273 0.80583 0.8027 ]]

 [[0.97311 0.92755 0.85433 0.83088]
  [0.95383 0.82447 0.95759 0.92816]
  [0.97823 0.86461 1.      0.88427]
  [0.89015 0.92902 0.94009 0.92819]]]
[0 0 0 ... 4 4 4]


In [76]:
tess=np.array([[1,2,3],[4,5,6]])
t=np.tile(tess,(2,1))
t

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [166]:
np.set_printoptions(threshold='none')
print label_a
train_sub=train_a[0:369,:,:]
label_sub=label_a[0:369]  
print label_a[409]

[0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1 0
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1
 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0
 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0
 0 0 0 0 0 1 1 1 1 1 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2]
2


In [5]:
gpu_options = tf.GPUOptions(allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
from random import randint,shuffle

train_a=X2
label_a=label2

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(1024,
                        #input_shape=(41000,),
                        activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(1024, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(3, activation=tf.nn.softmax)
])

for i in range(410):
    if label_a[i]==3:
        label_a[i]=1
    elif label_a[i]==4:
        label_a[i]=2

# tiling the data
train_sub=train_a[0:369,:,:]
train_lab=label_a[0:369]
valid_sub=train_a[369:410,:,:]
valid_lab=label_a[369:410]
m1=np.tile(train_sub,(100,1,1))
m2=np.tile(valid_sub,(100,1,1))
m3=np.tile(train_lab,(100,))
m4=np.tile(valid_lab,(100,))
label_input=np.concatenate([m3,m4])
train_input=np.concatenate([m1,m2])

train_input1=np.tile(train_a,(100,1,1))
label_input1=np.tile(label_a,(100,))


np.set_printoptions(threshold='none')

model.compile(
    optimizer='adam',
    #optimizer=tf.keras.optimizers.SGD(lr=0.001, momentum=0.9, nesterov=True),
                #loss=tf.keras.losses.categorical_crossentropy,
                loss='sparse_categorical_crossentropy',
                #loss=tf.losses.softmax_cross_entropy,
                # pred=tf.nn.softmax(tf.add(tf.matmul(X1,W),b)) ,
                # cost =tf.reduce_mean(-tf.reduce_sum(label1*tf.log(pred),reduction_indices=1)),
                #loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_input, label_input, validation_split=0.1, epochs=5)
model.evaluate(train_input,label_input)

# print label1[368:409]

Train on 36900 samples, validate on 4100 samples
Epoch 1/5
36900/36900 [==============================] - 4s 119us/step - loss: 0.2385 - acc: 0.8844 - val_loss: 0.1302 - val_acc: 0.9756
Epoch 2/5
36900/36900 [==============================] - 4s 105us/step - loss: 0.1671 - acc: 0.9188 - val_loss: 0.0780 - val_acc: 1.0000
Epoch 3/5
36900/36900 [==============================] - 4s 109us/step - loss: 0.1446 - acc: 0.9339 - val_loss: 0.0988 - val_acc: 0.9268
Epoch 4/5
36900/36900 [==============================] - 4s 105us/step - loss: 0.1259 - acc: 0.9437 - val_loss: 0.1812 - val_acc: 0.9268
Epoch 5/5
41000/41000 [==============================] - 1s 34us/step


[0.16506306191770043, 0.926829268292683]

In [201]:
label_input.shape

(41000, 4, 4)

In [102]:
label_a.s

(409,)

In [68]:
tess=[]
tess=np.array(tess)

In [77]:
tess

array([], dtype=int64)

In [4]:
sess.close()

In [51]:
label1

array([[0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [1.],

In [6]:
sess = tf.Session()
#print sess.run(model.fit)
sess.close()

In [26]:
test=np.reshape(X1[399],(1,4,4))

In [6]:
test.shape

(1, 4, 4)

In [25]:
np.set_printoptions(threshold='none')
#label1
y

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14,
       14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19,
       19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23,
       23, 23, 23, 23, 23

In [27]:
label1[399]

array([2.])

In [9]:
print(model.predict(test,batch_size=10,verbose=0))

[[5.5517238e-03 7.3542947e-06 9.9444085e-01]]


In [28]:
print(model.predict_classes(test,batch_size=10,verbose=0))

[2]
